### ISSUE TITLE
Add Topic Proportions Calculator

### ISSUE THREAD

**Issue by avkoehl** [hugomailhot/corpus-explorer#14]
Motivation 
===
We need a way of computing topic proportions based on subset or whole doc topics matrix.
The topic proportions are obviously the crucial element of the visualization as they are the only changing aspect.
Computation of topic proportion is quite simple:
```
colsums(doc_topics * doc_lengths)/sum(doc_topics * doc_lengths)
```
The doc_topics is either the full matrix or just the rows we care about after filtering.

Deliverable 
===
A submodule that computes topic proportions based on specified subset (or full thing) of documents.

**input**

+ document_ids (list of ints)
+ doc_topics (however we currently store this)
+ document_lengths (however we currently store this)

**output**

+ topic_proportions (list of proportions with length == ntopics)

**Comment by hugomailhot** [comment]
Am I correct in assuming you meant to put `doctopics` and not `docterm` in the input section, and that we should replace `topic_proportions` by `document_lengths` in the motivation section?

**Comment by hugomailhot** [comment]
Here's a minimal version of it: https://github.com/hugomailhot/corpus-explorer/blob/d6c25b37449f3988f5e5c11def0fe6a537097b04/corpus_explorer/utils.py#L82-L101

Learned [this trick](https://stackoverflow.com/questions/18522216/multiplying-across-in-a-numpy-array#answer-45895371) to do it with `numpy`.

I'm not handling the case where we want to subset the collection and only compute the proportions on part of it. I thought we might prefer to subset the collection before-hand, and only pass that subset to `get_topic_proportions`, who doesn't need to know whether it's a full corpus or not. The option is still open if we need it, I just prefer starting with the simplest case.

Writing this, I started to want to use numpy and scipy instead of pandas whenever possible.

**Comment by hugomailhot** [comment]
Here's a minimal version of it: https://github.com/hugomailhot/corpus-explorer/blob/d6c25b37449f3988f5e5c11def0fe6a537097b04/corpus_explorer/utils.py#L82-L101

Learned [this trick](https://stackoverflow.com/questions/18522216/multiplying-across-in-a-numpy-array#answer-45895371) to do it with `numpy`.

I'm not handling the case where we want to subset the collection and only compute the proportions on part of it. I thought we might prefer to subset the collection before-hand, and only pass that subset to `get_topic_proportions`, who doesn't need to know whether it's a full corpus or not. The option is still open if we need it, I just prefer starting with the simplest case.

Writing this, I started to want to use numpy and scipy instead of pandas whenever possible.

I'll write some unit tests for it before putting up a PR.

**Comment by avkoehl** [comment]
> Am I correct in assuming you meant to put `doctopics` and not `docterm` in the input section, and that we should replace `topic_proportions` by `document_lengths` in the motivation section?

Yes to both, I should proofread. Editing original issue to reflect this

**Comment by avkoehl** [comment]
> I'm not handling the case where we want to subset the collection and only compute the proportions on part of it. I thought we might prefer to subset the collection before-hand, and only pass that subset to `get_topic_proportions`, who doesn't need to know whether it's a full corpus or not. The option is still open if we need it, I just prefer starting with the simplest case.

Yes this is what I meant. This function simply sees a doc topics matrix, it has no idea if its the full thing or just a subset of the rows, it doesn't care: processes both the same way

**Comment by hugomailhot** [comment]
Alright, perfect.
