### ISSUE TITLE
Add Visualization Generator 

### ISSUE THREAD

**Issue by avkoehl** [hugomailhot/corpus-explorer#16]
Motivation 
===
This is the main module that generates the plotly scatter plot visualization of the topic model and topic proportions.
For now, no need to show the topic terms on the side --this and other features (such as hover info, etc.) can be added later.
The scatter plot is simply each topic plotted at an x and y coordinate with radius of the marker coming from the topic proportion for that topic.

Deliverable 
===
A submodule that generates a plotly scatter plot given topic proportions and topic coordinates.

**input**

+ topic_proportions
+ topic_coordinates

**output**

+ plotly plot

**Comment by hugomailhot** [comment]
I have a notebook example that can take a dataset as input, train a 3-topics LDA model, and output this in the end:

![image](https://user-images.githubusercontent.com/5240492/69907465-aa316580-138a-11ea-9488-cfb8293a97ee.png)

It seems like I confused axes somewhere in the existing code since I had to change a numpy summation axis somewhere, which breaks unit testing.

So all-in-all this will work, but I need another session to fix a small bug.

**Comment by hugomailhot** [comment]
Turns out the axis summation thing was a symptom of a more subtle bug I had, which happened because I wasn't aware of different behaviors between identically shaped scipy sparse matrices, numpy matrices, and 2D `np.array` objects.
