### ISSUE TITLE
Set up package management with poetry

### ISSUE THREAD

**Issue by hugomailhot** [hugomailhot/corpus-explorer#4]
# Motivation

[poetry](https://poetry.eustace.io/) provides an elegant solution to Python module packaging and dependency management. Using it has the immediate benefit that the code works the same on all dev stations, and the eventual benefit of greatly simplifying packaging for distribution.

# Deliverable

- [x] The repo can be installed for local development using poetry
- [x] The README is updated to explain how to develop for the project using poetry

**Comment by hugomailhot** [comment]
Closed by #5

**Comment by avkoehl** [comment]
Followed the steps of the README on ubuntu 18.04. Worked fine. 

I like the idea of using poetry. However not 100% sold on the added complexity of users having to use pyenv and poetry instead of just a requirements.txt file. I am not sure about the portability of poetry, I would assume its written entirely in python and can work on mac windows or linux. Windows users will have a hard time with the CLI, but there is now way around that.

In addition, I am confused by the 46 packages that poetry installed on my system. I am assuming they were all dependencies of gensim, pandas, pyarrow and pytest as I don't see them listed in pyproject.toml. If that is the case, that is totally fine.

**For now while we develop this seems worth it because dependency management is a huge time sink.**

**Comment by hugomailhot** [comment]
>Followed the steps of the README on ubuntu 18.04. Worked fine.

Awesome.

>I like the idea of using poetry. However not 100% sold on the added complexity of users having to use pyenv and poetry instead of just a requirements.txt file. I am not sure about the portability of poetry, I would assume its written entirely in python and can work on mac windows or linux. Windows users will have a hard time with the CLI, but there is now way around that.

Yeah this is definitely a bit more involved than just using requirements.txt. It does also take care of the virtualenv, which is always nice. I believe down the line this is also useful for packaging into a module, and I know for sure that the eventual package user would never need to know about it. 

People doing dev work on the project on the other hand will need to use the CLI, yes, so if we have a Windows-using collaborator and it causes problem, we'd have to revise that for sure.

>In addition, I am confused by the 46 packages that poetry installed on my system. I am assuming they were all dependencies of gensim, pandas, pyarrow and pytest as I don't see them listed in pyproject.toml. If that is the case, that is totally fine.

Yep, that's poetry at work right there.
